### ISSUE TITLE
Как определять откуда залогинился текущий пользователь?

### ISSUE THREAD

**Issue by Baksalyar** [marazmiki/django-ulogin#37]
В доках не нашел такого, и пока не соображу. Например, залогинился я в свой аккаунт через vk, а позже залогинился в него же через Яндекс. И требуется узнать, откуда залогинен текущий пользователь. Как это правильно сделать имеющимися средствами? Или нужно допиливать?

**Comment by marazmiki** [comment]
Ох, я уже всё забыл :)

Но вот навскидку: согласно [вот этому куску](https://github.com/marazmiki/django-ulogin/blob/master/django_ulogin/views.py#L107), в ответе от ULogin есть ключ `network`. В нём, похоже, и должно быть кодовое имя провайдера.

**Comment by Baksalyar** [comment]
Хм. Не совсем понятно. К примеру, в шаблоне я проверяю, аутентифицирован ли пользователь так:

```
{% if request.user.is_authenticated %}
```

Затем, если пользователь аутентифицирован, я хочу показать из какой соцсети он зашел. Как это сделать в шаблоне? На ум приходит лишь взять первого попавшегося связанного юзера:

```
{{ request.user.ulogin_users.first.network }}
```

Но это ненадежно и неправильно, потому что с одним пользователем может быть связано множество аккаунтов соцсетей. Пока что ума не приложу, как имеющимися средствами узнать, какому аккаунту соцсети (пользователю ULogin) соответствует текущий залогиненный Django-пользователь.

**Comment by marazmiki** [comment]
Вот оно что. Речь, значит, идёт о слое view. Это нужно было бы сразу уточнить.

С существующим подходом задача из коробки не решается. Хотя бы потому из тех соображений, что после успешной аутентификации пользователя редиректит на другую страницу и, соответственно, значение `ulogin_user` в любом случае потеряется.

С другой стороны, при успешной аутентификации пользователя [шлётся сигнал assign](https://github.com/marazmiki/django-ulogin/blob/master/django_ulogin/views.py#L146), содержащий  в себе объект `ULoginUser`, так что можно сколхозить.

Вы можете написать обработчик, который ловит этот сигнал и, например, сохраняет `ulogin_user` в кеш. Далее, можно написать или темплейт-тег, или контекст-процессор, который бы извлекал значение этого кеша.

**Comment by Baksalyar** [comment]
Ага, вот как раз было интересно — есть ли какой-то «стандартный» метод решить это из коробки. Так то навесить костылей через сигналы понятно что можно. Попробую сколхозить, спасибо.

**Comment by marazmiki** [comment]
Сигналы и есть стандартный метод, рекомендуемый джангой. А то, что где-то там в шаблонах переменная недоступна — это как раз частный случай, его решать в приложениях общего назначения не нужно.
