### ISSUE TITLE
Проблема с тестами

### ISSUE THREAD

**Issue by simon-db** [marazmiki/django-ulogin#38]
Django 1.8.6
БД Postgresql
Версии Ulogin 0.2.3 

Если на сайте используется кастомная модель пользователя (созданная через AbstractBaseUser), то при попытке запустить тест происходит ошибка создания тестовой базы данных. "django.db.utils.ProgrammingError: relation "site_user_siteuser" does not exist"
Я посмотрел, как Djnago создает тестовую базу данных. 
1) Он создает саму базу
2) Создает таблицу миграций
3) Создает таблицу django_ulogin_uloginuser
4) Пытается вешать FOREIGN KEY на таблицу кастомного пользователя, которой еще нет. 
Из-за этого и вылазит исключение.
Проблема решается добавлением директории migrations в ulogin и созданием "начальной" миграции.
В этом случае тестовая база данных создается успешно. Таблица "django_ulogin_uloginuser" теперь создается позже модели пользователя.

**Comment by marazmiki** [comment]
Здравствуйте!

Проблема с миграциями уже возникала (см #31). Тогда я [попытался объяснить](https://github.com/marazmiki/django-ulogin/issues/31#issuecomment-157587872), почему мне не  хотелось бы добавлять миграции в сам проект.

Однако сейчас поддержка старых версий Джанго выброшена, так что, возможно, и имеет смысл сделать "единственную" миграцию. А заодно и проверить, как это всё работает на `Django==1.10` и `Python 3.6`

А пока issue не закрыт, Вы можете воспользоваться советом про `MIGRATION_MODULES` ([там же, в #31](https://github.com/marazmiki/django-ulogin/issues/31#issuecomment-157672342))

**Comment by simon-db** [comment]
Ясно, спасибо за совет с MIGRATION_MODULES, обязательно попробую.

**Comment by marazmiki** [comment]
В ``1.0.0`` используются штатные миграции Django, т.е. это всё неактуально
