### ISSUE TITLE
Редирект в https

### ISSUE THREAD

**Issue by Baksalyar** [marazmiki/django-ulogin#40]
Сервер настроен таким образом, что редиректит все http-запросы на соответствующие https.

Однако в виджет при этом подставляется redirect_uri=http://..., и postback происходит на http://.../?next=http://... Nginx, естественно, автоматом редиректит это на https и все ломается.

Пока не сообразил как это правильно починить. Что можно сделать?

Django 2.0.7
django-ulogin с github-а.

**Comment by Baksalyar** [comment]
В качестве временного решения делаю в Nginx-е редирект 307 с сохранением данных POST для /ulogin/postback.

**Comment by marazmiki** [comment]
Здравствуйте.Может, я чего-то не пониманю, но почему бы не указать правильное (т.е. с префиксом `https://` ) значение `ULOGIN_REDIRECT_URL` в`settings.py`?

**Comment by Baksalyar** [comment]
Хм. Спасибо, попробую. Этого момента я нигде не нарыл, могу ошибаться, но в доках такого нет и даже гуглом оно не гуглится.
